
#
##
### Written by the CAT (Cloudwatt Automation Team)
##

   - hosts: local
     user: cloud
     become: true
     vars:
     domain: "{{ mail_domain }}"
  tasks:
    - name: desired locale are present
      locale_gen: name="{{ item }}" state=present
      with_items:
        - fr_FR.UTF-8
        - en_US.UTF-8
    - name: apt-get update & upgrade
      apt:
        upgrade=full
        update_cache=yes
        cache_valid_time=3600

    - name: packages installed
      apt:
        pkg={{ item }}
        state=present
      with_items:
        - postfix
        - dovecot-common
        - dovecot-imapd
        - dovecot-pop3d
        - clamav
        - clamav-daemon
        - clamsmtp
        - clamav-freshclam
        - apache2
        - mysql-server
        - php5
        - libapache2-mod-php5
        - php5-mysql
        - php5-mcrypt
        - roundcube
        - roundcube-plugins
        - roundcube-plugins-extra
        - git


 #   - name: Let's encrypt install
 #    git:
 #       repo=https://github.com/letsencrypt/letsencrypt
 #       dest=/root/letsencrypt

    - name: create self-signed SSL cert
      shell: openssl req -new -nodes -x509 -subj "/C=FR/ST=ILE DE FRANCE/L=PARIS/O=CLOUDWATT/CN={{ domain }}" -days 3650 -keyout /root/server.key -out /root/server.crt -extensions v3_ca creates=/root/server.crt
    #- name: Generate let's encrypt certificate
    #  shell: |
    #  sudo /root/letsencrypt/letsencrypt-auto certonly --standalone --agree-tos --email vagrant@vagrant.fr -d vagrant.fr >/dev/null 2>&1

  #  - name: Add key in postfix
  #   shell: |
  #     sudo /usr/sbin/postconf -e 'smtpd_tls_key_file = /etc/letsencrypt/keys/0000_key-letsencrypt.pem'


    - name: main postfix configuration
      copy:
       src=main.cf
        dest=/etc/postfix/main.cf
        owner=root
        group=root
        mode=0644
      notify: restart postfix

    - name: deconf postfix
      debconf:
        name="{{ item.name }}"
        question="{{ item.question }}"
        value="{{ item.value }}"
        vtype="{{ item.vtype }}"
      with_items:

        - { name: 'postfix', question: 'postfix/main_mailer_type', vtype: 'string', value: "Internet Site"}
        - { name: 'postfix', question: 'postfix/mailname', vtype: 'string', value: "{{ domain }}"}

    - name: clamAv configuration
      copy:
        src=clamsmtpd.conf
        dest=/etc/clamsmtpd.conf
        owner=root
        group=root
        mode=0644
      notify: restart clamav-daemon

    - cron: name="update ClamAV" minute="00" hour="1" job="/usr/bin/freshclam --quiet"

    - name: master postfix configuration and clamAv
      copy:
       src=master.cf
        dest=/etc/postfix/master.cf
        owner=root
        group=root
        mode=0644
      notify: restart postfix

    - name: auth dovecot
      lineinfile:
        name=/etc/dovecot/conf.d/10-auth.conf
        regexp="^auth_mechanisms \= plain"
        line="auth_mechanisms = plain login"
      notify: restart dovecot

    - name: email inbox
      lineinfile:
        name=/etc/dovecot/conf.d/10-mail.conf
        regexp="^mail_location \= mbox:~/mail:INBOX\=/var/mail/%u"
        line="mail_location = maildir:~/Maildir"
      notify: restart dovecot

    - name: pop3
      lineinfile:
        name=/etc/dovecot/conf.d/20-pop3.conf
        regexp="^#pop 3_uidl_format \= %08Xu%08Xv"
        line="pop3_uidl_format = %08Xu%08Xv"
      notify: restart dovecot


    - name: roundcube Alias 1
      lineinfile:
        name=/etc/roundcube/apache.conf
        regexp="^#Alias /roundcube/program/js/tiny_mce/ /usr/share/tinymce/www/"
        line="Alias /roundcube/program/js/tiny_mce/ /usr/share/tinymce/www/"
      notify: restart apache

    - name: roundcube Alias 2
      lineinfile:
        name=/etc/roundcube/apache.conf
        regexp="^#Alias /roundcube /var/lib/roundcube"
        line="Alias /roundcube /var/lib/roundcube"
      notify: php5enmod mcrypt



    - name: add virtualhost & ssl for roundcube
       template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/vhost.conf
       notify: enable roundcube site

    - name: roundcube Alias 1
      lineinfile:
        name=/etc/roundcube/main.inc.php
        regexp="^$rcmail_config['default_host'] = '';"
        line="$rcmail_config['default_host'] = '{{ domain }}';"
      notify: restart apache



  handlers:
    - name: restart postfix
      service: name=postfix state=restarted
    - name: restart dovecot
      service: name=dovecot state=restarted
    - name: restart clamav-daemon
      service: name=clamav-daemon state=restarted
    - name: restart apache
      service: name=apache2 state=restarted
    - name: php5enmod mcrypt
      shell: php5enmod mcrypt
      notify: restart apache
    - name: enable roundcube site
      shell: /usr/sbin/a2enmod ssl && /usr/sbin/a2enmod rewrite && /usr/sbin/a2dissite 000-default default-ssl.conf && a2ensite vhost.conf
      notify: restart apache





