---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##

- hosts: local
  user: cloud
  become: true

  tasks:
    - name: desired locale are present
      locale_gen: name="{{ item }}" state=present
      with_items:
        - fr_FR.UTF-8
        - en_US.UTF-8

    - name: apt-get update & upgrade
      apt:
        upgrade=full
        update_cache=yes
        cache_valid_time=3600

    - name: packages installed
      apt:
        pkg={{ item }}
        state=present
      with_items:
        - postfix
        - dovecot-core
        - dovecot-imapd
        - dovecot-pop3d
        - mailutils
        - clamav
        - clamav-daemon
        - clamsmtp
        - clamav-freshclam
        - apache2
        - mysql-server
        - php5
        - libapache2-mod-php5
        - php5-mysql
        - php5-mcrypt
        - roundcube
        - roundcube-plugins
        - roundcube-plugins-extra
        - git

    - name: include variables
      include_vars: /etc/ansible/mail-vars.yml

    - name: stop apache
      service: name=apache2 state=stopped

    - name: Let's encrypt download
      git:
        repo=https://github.com/letsencrypt/letsencrypt
        dest=/root/letsencrypt



    - name: Generate let's encrypt certificate
      shell: |
          cd /root/letsencrypt/
          ./letsencrypt-auto-source/letsencrypt-auto --os-packages-only
          ./tools/venv.sh
           source ./venv/bin/activate
           letsencrypt certonly --standalone --agree-tos --email root@{{ mail_domain }} -d {{ mail_domain }} --standalone-supported-challenges tls-sni-01

    - name: Copy crt to cozy
      file:
        src={{ item.src }}
        dest={{ item.dest }}
        state=link
      with_items:
        - {src: "/etc/letsencrypt/live/{{ mail_domain }}/privkey.pem", dest: "/root/server.key" }
        - {src: "/etc/letsencrypt/live/{{ mail_domain }}/fullchain.pem", dest: "/root/server.crt" }


    - name: Cron renew crt
      cron:
        name="renew crt"
        special_time=monthly
        job="/root/renew_cert.sh"



    - name: configuration main postfix
      template: src=main.cf.j2 dest=/etc/postfix/main.cf


    - name: configuration master postfix
      copy:
       src=master.cf
        dest=/etc/postfix/master.cf
        owner=root
        group=root
        mode=0644

    -name: Cron upate ClamAV
     cron:
        name="update ClamAV"
        minute="00"
        hour="1"
        job="/usr/bin/freshclam --quiet"


    - name: dovecot configuration
      replace:
        dest="{{ item.dest }}"
        regexp="{{ item.regexp }}"
        replace="{{ item.replace }}"
      with_items:
        - { dest: '/etc/dovecot/dovecot.conf', regexp: '^#listen = *, ::', replace: 'listen = *, ::'}
        - { dest: '/etc/dovecot/conf.d/10-mail.conf', regexp: '^mail_location \= mbox:~/mail:INBOX\=/var/mail/%u', replace: 'mail_location = maildir:~/Maildir'}
        - { dest: '/etc/dovecot/conf.d/10-auth.conf', regexp: '^#disable_plaintext_auth = yes', replace: 'disable_plaintext_auth = no'}
        - { dest: '/etc/dovecot/conf.d/10-auth.conf', regexp: '^auth_mechanisms = plain$', replace: 'auth_mechanisms = plain login'}
        - { dest: '/etc/dovecot/conf.d/10-ssl.conf', regexp: '^#ssl = yes', replace: 'ssl = no'}
        - { dest: '/etc/dovecot/conf.d/10-ssl.conf', regexp: '^ssl_cert = </etc/dovecot/dovecot.pem$', replace: '#ssl_cert = </etc/dovecot/dovecot.pem'}
        - { dest: '/etc/dovecot/conf.d/10-ssl.conf', regexp: '^ssl_key = </etc/dovecot/private/dovecot.pem$', replace: '#ssl_key = </etc/dovecot/private/dovecot.pem'}
        - { dest: '/etc/dovecot/conf.d/20-pop3.conf', regexp: '^#pop_3_uidl_format \= %08Xu%08Xv', replace: 'pop3_uidl_format = %08Xu%08Xv'}



    - name: master dovecot configuration
      copy:
        src=10-master.conf
        dest=/etc/dovecot/conf.d/10-master.conf
        owner=root
        group=root
        mode=0644
      notify: restart postfix


    - name: stop dovecot
      shell: initctl stop dovecot

    - name: start dovecot
      shell: initctl start dovecot


    - name: roundcube configuration
      replace:
        dest="{{ item.dest }}"
        regexp="{{ item.regexp }}"
        replace="{{ item.replace }}"
      with_items:
        - { dest: '/etc/roundcube/apache.conf', regexp: '^#    Alias /roundcube/program/js/tiny_mce/ /usr/share/tinymce/www/', replace: 'Alias /roundcube/program/js/tiny_mce/ /usr/share/tinymce/www/'}
        - { dest: '/etc/roundcube/apache.conf', regexp: '^#    Alias /roundcube /var/lib/roundcube', replace: 'Alias /roundcube /var/lib/roundcube'}


    - name: roundcube add domaine
      lineinfile:
        name=/etc/roundcube/main.inc.php
        regexp="^$rcmail_config['default_host'] = '';"
        line="$rcmail_config['default_host'] = '{{  mail_domain }}';"
      notify: php5enmod mcrypt



    - name: add virtualhost
      template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/vhost.conf

    - name: php5enmod mcrypt
      shell: php5enmod mcrypt
      notify: enable roundcube
  handlers:
    - name: restart postfix
      service: name=postfix state=restarted
      notify: restart clamsmtp
    - name: restart clamav-daemon
      service: name=clamav-daemon state=restarted
    - name: restart clamsmtp
      service: name=clamsmtp state=restarted
      notify: restart clamav-daemon
    - name: enable roundcube
      shell: /usr/sbin/a2enmod ssl && /usr/sbin/a2enmod rewrite && /usr/sbin/a2dissite 000-default default-ssl.conf && /usr/sbin/a2ensite vhost.conf
      notify: restart apache
    - name: restart apache
      service: name=apache2 state=restarted

